function New-WingetterReadmeMarkdown {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        $AppDetails,

        [Parameter(Mandatory)]
        [string]$InstallerFileName,

        [Parameter(Mandatory)]
        [string]$InstallerHash,

        [Parameter(Mandatory)]
        [string]$InstallCommandLine,

        [Parameter(Mandatory)]
        [string]$UninstallCommandLine,

        [string]$IntuneWinFileName,
        [string]$IconPath,
        [hashtable]$Win32LobAppJson
    )

    $generatedAt = Get-Date -Format 'yyyy-MM-dd HH:mm:ss UTC'
    $iconStatus = if ($IconPath -and (Test-Path $IconPath)) { 'Available (`icon.png`)' } else { 'Not available' }

    $returnCodesTable = @'
| Return Code | Type | Description |
|-------------|------|-------------|
| 0 | success | Installation completed successfully |
| 1707 | success | Installation completed successfully (alternate) |
| 3010 | softReboot | Success, soft reboot required |
| 1641 | hardReboot | Success, hard reboot required |
| 1618 | retry | Another installation is in progress |
'@

    $detectionInfo = 'PowerShell script (`detection.ps1`) — registry-based, no Winget dependency on managed devices.'
    $installInfo = 'PowerShell script (`install.ps1`) — executes installer with silent flags and IME transcript logging.'
    $uninstallInfo = 'PowerShell script (`uninstall.ps1`) — locates uninstall string from registry and runs silently.'

    return @"
# $($AppDetails.DisplayName)

> Generated by **Wingetter** on $generatedAt

## Application Overview

| Field | Value |
|-------|-------|
| **Display Name** | $($AppDetails.DisplayName) |
| **Package ID** | ``$($AppDetails.PackageId)`` |
| **Version** | $($AppDetails.Version) |
| **Publisher / Developer** | $($AppDetails.Publisher) |
| **Installer Type** | $($AppDetails.InstallerType) |
| **Homepage** | $($AppDetails.Homepage) |
| **Icon** | $iconStatus |

## Description

$($AppDetails.Description)

---

## Intune Win32 App Upload Reference

Use these values when creating a Win32 LOB app in the [Microsoft Intune admin center](https://endpoint.microsoft.com) or via Microsoft Graph API.

### App Information

| Intune Field | Value |
|--------------|-------|
| **Name** (displayName) | $($AppDetails.DisplayName) |
| **Description** | $($AppDetails.Description) |
| **Publisher** | $($AppDetails.Publisher) |
| **Developer** | $($AppDetails.Publisher) |
| **Owner** | *(set in Intune portal)* |
| **Notes** | Generated by Wingetter from Winget package ``$($AppDetails.PackageId)`` |
| **Category** | *(assign in Intune portal)* |
| **Show this as a featured app** | *(optional, set in portal)* |
| **Information URL** | $($AppDetails.Homepage) |
| **Privacy information URL** | *(optional)* |
| **Developer** | $($AppDetails.Publisher) |
| **Display version** | $($AppDetails.Version) |

### Program

| Intune Field | Value |
|--------------|-------|
| **Install command** | ``$InstallCommandLine`` |
| **Uninstall command** | ``$UninstallCommandLine`` |
| **Install behavior** | System |
| **Device restart behavior** | Determine behavior based on return codes |
| **Return codes** | See table below |
| **Setup file** | ``$InstallerFileName`` |
| **Content file (.intunewin)** | ``$IntuneWinFileName`` |
| **SHA256 (installer)** | ``$InstallerHash`` |

$returnCodesTable

### Requirements

| Intune Field | Value |
|--------------|-------|
| **Operating system architecture** | 64-bit |
| **Minimum operating system** | Windows 10 2004 (20H1) |
| **Disk space required (MB)** | *(verify installer size)* |
| **Physical memory required (MB)** | *(optional)* |
| **Minimum number of processors** | *(optional)* |
| **Additional requirement rules** | *(optional)* |

### Detection Rules

| Setting | Value |
|---------|-------|
| **Rule format** | Use a custom detection script |
| **Script file** | ``detection.ps1`` |
| **Run script as 32-bit process** | No |
| **Enforce script signature check** | No |
| **Description** | $detectionInfo |

### Dependencies & Supersedence

| Field | Value |
|-------|-------|
| **Dependencies** | *(configure in Intune if needed)* |
| **Supersedence** | *(configure when updating versions)* |

### Assignments

| Field | Value |
|-------|-------|
| **Required** | *(assign device/user groups)* |
| **Available for enrolled devices** | *(optional)* |
| **Uninstall** | *(optional)* |
| **App protection policy** | *(optional)* |

---

## Package Files

| File | Purpose |
|------|---------|
| ``$InstallerFileName`` | Downloaded installer from Winget |
| ``install.ps1`` | $installInfo |
| ``uninstall.ps1`` | $uninstallInfo |
| ``detection.ps1`` | $detectionInfo |
| ``icon.png`` | Application icon for Intune portal |
| ``app.json`` | Secondary metadata export |
| ``win32LobApp.json`` | Microsoft Graph ``#microsoft.graph.win32LobApp`` payload |
| ``packaging.log`` | Wingetter packaging run log |
| ``$IntuneWinFileName`` | Final Intune Win32 content package |

---

## Install & Uninstall Commands (Direct)

For reference, the raw installer command (without PowerShell wrapper) is:

``````powershell
$InstallCommandLine
``````

Intune should use the PowerShell wrapper commands from ``win32LobApp.json`` for consistent logging and error handling.

---

## Upload Steps

1. Open **Intune admin center** → **Apps** → **Windows** → **Add** → **Windows app (Win32)**
2. Upload ``$IntuneWinFileName``
3. Fill in app information using the tables above
4. Set install/uninstall commands from the **Program** section
5. Upload ``detection.ps1`` as the custom detection script
6. Configure requirements (x64, Windows 10 2004+)
7. Assign to target groups
8. Monitor deployment via **Device install status** and IME logs at:
   ``%ProgramData%\Microsoft\IntuneManagementExtension\Logs\``

---

## IME Log Files

| Log | Path |
|-----|------|
| Install | ``%ProgramData%\Microsoft\IntuneManagementExtension\Logs\$($AppDetails.PackageId)-install.log`` |
| Detection | ``%ProgramData%\Microsoft\IntuneManagementExtension\Logs\$($AppDetails.PackageId)-detection.log`` |
| Uninstall | ``%ProgramData%\Microsoft\IntuneManagementExtension\Logs\$($AppDetails.PackageId)-uninstall.log`` |

---

*This README was auto-generated by [Wingetter](https://github.com) from Winget package metadata.*
"@
}

function New-WingetterAppJson {
    param(
        $AppDetails,
        [string]$InstallerFileName,
        [string]$InstallerHash,
        [string]$InstallCommandLine,
        [string]$UninstallCommandLine
    )

    return @{
        packageIdentifier    = $AppDetails.PackageId
        displayName          = $AppDetails.DisplayName
        description          = $AppDetails.Description
        version              = $AppDetails.Version
        source               = 2
        publisher            = $AppDetails.Publisher
        informationUrl       = $AppDetails.Homepage
        publisherUrl         = $AppDetails.Homepage
        supportUrl           = $AppDetails.Homepage
        installerType        = 7
        installerUrl         = ''
        hash                 = $InstallerHash
        installCommandLine   = $InstallCommandLine
        uninstallCommandLine = $UninstallCommandLine
        installerFilename    = $InstallerFileName
        installerContext     = 2
        architecture         = 2
    }
}

function New-WingetterWin32LobAppJson {
    param(
        $AppDetails,
        [string]$InstallerFileName,
        [string]$InstallerBaseName,
        [string]$DetectionScript,
        [string]$InstallCommandLine,
        [string]$UninstallCommandLine,
        [string]$IconFilePath
    )

    $detectionScriptBase64 = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($DetectionScript))
    $iconBase64 = ''
    if ($IconFilePath -and (Test-Path $IconFilePath)) {
        $iconBytes = [System.IO.File]::ReadAllBytes($IconFilePath)
        $iconBase64 = [Convert]::ToBase64String($iconBytes)
    }

    $json = @{
        '@odata.type'                      = '#microsoft.graph.win32LobApp'
        description                        = $AppDetails.Description
        developer                          = $AppDetails.Publisher
        displayName                        = $AppDetails.DisplayName
        informationUrl                     = $AppDetails.Homepage
        notes                              = "Generated by Wingetter at $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') [Winget|$($AppDetails.PackageId)]"
        publisher                          = $AppDetails.Publisher
        fileName                           = "$InstallerBaseName.intunewin"
        allowAvailableUninstall            = $true
        applicableArchitectures            = 'x64'
        detectionRules                     = @(
            @{
                '@odata.type'           = '#microsoft.graph.win32LobAppPowerShellScriptDetection'
                enforceSignatureCheck = $false
                runAs32Bit              = $false
                scriptContent           = $detectionScriptBase64
            }
        )
        displayVersion                     = $AppDetails.Version
        installCommandLine                 = $InstallCommandLine
        installExperience                  = @{
            deviceRestartBehavior = 'basedOnReturnCode'
            runAsAccount          = 'system'
        }
        minimumSupportedOperatingSystem    = @{ v10_2004 = $true }
        minimumSupportedWindowsRelease     = '2004'
        returnCodes                        = @(
            @{ returnCode = 0; type = 'success' }
            @{ returnCode = 1707; type = 'success' }
            @{ returnCode = 3010; type = 'softReboot' }
            @{ returnCode = 1641; type = 'hardReboot' }
            @{ returnCode = 1618; type = 'retry' }
        )
        setupFilePath                      = $InstallerFileName
        uninstallCommandLine               = $UninstallCommandLine
    }

    if ($iconBase64) {
        $json.largeIcon = @{
            type  = 'image/png'
            value = $iconBase64
        }
    }

    return $json
}
