function Get-WingetterDisplayNameTokens {
    param(
        [Parameter(Mandatory = $true)]
        [string]$DisplayName,

        [Parameter(Mandatory = $true)]
        [string]$PackageId
    )

    $tokens = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)

    foreach ($word in ($DisplayName -split '\s+')) {
        $trimmed = $word.Trim()
        if ($trimmed.Length -gt 2) {
            [void]$tokens.Add($trimmed)
        }
    }

    foreach ($part in ($PackageId -split '\.')) {
        $trimmed = $part.Trim()
        if ($trimmed.Length -gt 2) {
            [void]$tokens.Add($trimmed)
        }
    }

    return @($tokens)
}

function Get-WingetterRegistryVersion {
    param(
        [Parameter(Mandatory = $true)]
        $RegistryKey
    )

    $displayVersion = if ($RegistryKey.DisplayVersion) { "$($RegistryKey.DisplayVersion)".Trim() } else { '' }
    $displayName = if ($RegistryKey.DisplayName) { "$($RegistryKey.DisplayName)".Trim() } else { '' }

    if ($displayName -match '(?<version>\d{4}\.\d+(?:\.\d+){1,2})') {
        return $matches['version']
    }

    if ($displayName -match '(?<version>\d+\.\d+\.\d+(?:\.\d+)?)') {
        $candidate = $matches['version']
        if ($displayVersion -match '^\d{2,3}\.\d+\.\d+$' -or $candidate -ne $displayVersion) {
            return $candidate
        }
    }

    return $displayVersion
}

function New-WingetterInstallScript {
    param(
        [Parameter(Mandatory = $true)]
        [string]$PackageId,

        [Parameter(Mandatory = $true)]
        [string]$DisplayName,

        [Parameter(Mandatory = $true)]
        [string]$Version,

        [Parameter(Mandatory = $true)]
        [string]$InstallCommand
    )

    return @"
# Install script for $DisplayName
# Intune Win32 app deployment - generated by Wingetter

`$ErrorActionPreference = 'Stop'
`$packageId = '$PackageId'
`$displayName = '$DisplayName'
`$expectedVersion = '$Version'
`$logPath = "`$env:ProgramData\Microsoft\IntuneManagementExtension\Logs\`$packageId-install.log"

Start-Transcript -Path `$logPath -Force
Write-Host "Starting install for `$displayName (`$packageId) version `$expectedVersion"

try {
    `$scriptRoot = Split-Path -Parent `$MyInvocation.MyCommand.Path
    Set-Location -Path `$scriptRoot

    `$installCommand = @'
$InstallCommand
'@

    Write-Host "Executing install command: `$installCommand"
    `$process = Start-Process -FilePath 'cmd.exe' -ArgumentList "/c `$installCommand" -Wait -PassThru -NoNewWindow

    switch (`$process.ExitCode) {
        0 { Write-Host 'Install completed successfully.'; Stop-Transcript; exit 0 }
        3010 { Write-Host 'Install completed successfully (reboot required - 3010).'; Stop-Transcript; exit 3010 }
        1641 { Write-Host 'Install completed successfully (hard reboot required - 1641).'; Stop-Transcript; exit 1641 }
        1618 { Write-Host 'Another installation is already in progress (1618).'; Stop-Transcript; exit 1618 }
        default {
            Write-Host "Install failed with exit code `$(`$process.ExitCode)"
            Stop-Transcript
            exit `$process.ExitCode
        }
    }
}
catch {
    Write-Host "Install error: `$_"
    Stop-Transcript
    exit 1
}
"@
}

function New-WingetterDetectionScript {
    param(
        [Parameter(Mandatory = $true)]
        [string]$PackageId,

        [Parameter(Mandatory = $true)]
        [string]$DisplayName,

        [Parameter(Mandatory = $true)]
        [string]$Version
    )

    $tokens = Get-WingetterDisplayNameTokens -DisplayName $DisplayName -PackageId $PackageId
    $searchTerms = @('*' + $DisplayName + '*')
    foreach ($token in $tokens) {
        $searchTerms += '*' + $token + '*'
    }
    $searchTerms = $searchTerms | Select-Object -Unique
    $searchTermsLiteral = ($searchTerms | ForEach-Object { "'$_'" }) -join ', '

    return @"
# Registry-based detection script for $DisplayName
# Intune Win32 app deployment - generated by Wingetter

`$ErrorActionPreference = 'Continue'
`$packageId = '$PackageId'
`$version = '$Version'
`$displayName = '$DisplayName'
`$logPath = "`$env:ProgramData\Microsoft\IntuneManagementExtension\Logs\`$packageId-detection.log"

Start-Transcript -Path `$logPath -Force
Write-Host "Starting `$packageId `$version detection (registry-based)"

`$registryPaths = @(
    'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*',
    'HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*'
)

`$searchTerms = @($searchTermsLiteral)
`$allMatchingVersions = @()

foreach (`$regPath in `$registryPaths) {
    try {
        `$allKeys = Get-ItemProperty `$regPath -ErrorAction SilentlyContinue
        if (-not `$allKeys) { continue }

        `$uninstallKeys = `$allKeys | Where-Object {
            `$key = `$_
            foreach (`$term in `$searchTerms) {
                if ((`$key.DisplayName -and `$key.DisplayName -like `$term) -or (`$key.PSChildName -and `$key.PSChildName -like `$term)) {
                    return `$true
                }
            }
            return `$false
        }

        foreach (`$key in `$uninstallKeys) {
            Write-Host "Found registry key: `$(`$key.PSChildName) | DisplayName: `$(`$key.DisplayName) | DisplayVersion: `$(`$key.DisplayVersion)"

            `$nameMatch = `$false
            foreach (`$term in `$searchTerms) {
                `$token = `$term.Trim('*')
                if (`$token.Length -gt 2 -and `$key.DisplayName -and `$key.DisplayName -like "*`$token*") {
                    `$nameMatch = `$true
                    break
                }
            }

            if (-not `$nameMatch) { continue }

            `$versionToUse = `$null
            `$displayVersion = if (`$key.DisplayVersion) { "`$(`$key.DisplayVersion)".Trim() } else { '' }
            `$keyDisplayName = if (`$key.DisplayName) { "`$(`$key.DisplayName)".Trim() } else { '' }

            if (`$keyDisplayName -match '(?<extracted>\d{4}\.\d+(?:\.\d+){1,2})') {
                `$versionToUse = `$matches['extracted']
                Write-Host "Extracted version from DisplayName: `$versionToUse"
            }
            elseif (`$keyDisplayName -match '(?<extracted>\d+\.\d+\.\d+(?:\.\d+)?)') {
                `$candidate = `$matches['extracted']
                if (`$displayVersion -match '^\d{2,3}\.\d+\.\d+$' -or `$candidate -ne `$displayVersion) {
                    `$versionToUse = `$candidate
                    Write-Host "Extracted version from DisplayName: `$versionToUse"
                }
            }

            if (-not `$versionToUse) {
                `$versionToUse = `$displayVersion
            }

            if (`$versionToUse) {
                `$allMatchingVersions += [PSCustomObject]@{
                    DisplayName = `$key.DisplayName
                    DisplayVersion = `$versionToUse
                }
            }
        }
    }
    catch {
        Write-Host "Error checking registry path `$regPath : `$_"
    }
}

if (`$allMatchingVersions.Count -eq 0) {
    Write-Host "`$packageId not detected in registry, exiting with code 1"
    Stop-Transcript
    exit 1
}

`$installedVersion = if (`$allMatchingVersions.Count -eq 1) {
    `$allMatchingVersions[0].DisplayVersion
}
else {
    (`$allMatchingVersions | Sort-Object {
        try { [version]`$_.DisplayVersion } catch { [version]'0.0.0' }
    } -Descending | Select-Object -First 1).DisplayVersion
}

Write-Host "Detected version: `$installedVersion"

if ([string]::IsNullOrWhiteSpace(`$version)) {
    Stop-Transcript
    exit 0
}

try {
    if ([version]`$installedVersion -ge [version]`$version) {
        Write-Host "`$packageId is installed with version `$installedVersion (>= expected `$version)"
        Stop-Transcript
        exit 0
    }

    Write-Host "`$packageId installed version `$installedVersion is lower than expected `$version"
    Stop-Transcript
    exit 1
}
catch {
    if ("`$installedVersion" -ge "`$version") {
        Stop-Transcript
        exit 0
    }

    Stop-Transcript
    exit 1
}
"@
}

function New-WingetterUninstallScript {
    param(
        [Parameter(Mandatory = $true)]
        [string]$PackageId,

        [Parameter(Mandatory = $true)]
        [string]$DisplayName
    )

    $tokens = Get-WingetterDisplayNameTokens -DisplayName $DisplayName -PackageId $PackageId
    $firstToken = if ($tokens.Count -gt 0) { $tokens[0] } else { $DisplayName }

    return @"
# Uninstall script for $DisplayName
# Intune Win32 app deployment - generated by Wingetter

`$ErrorActionPreference = 'Stop'
`$packageId = '$PackageId'
`$displayName = '$DisplayName'
`$logPath = "`$env:ProgramData\Microsoft\IntuneManagementExtension\Logs\`$packageId-uninstall.log"

Start-Transcript -Path `$logPath -Force
Write-Host "Starting uninstall for `$displayName (`$packageId)"

`$registryPaths = @(
    'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*',
    'HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*'
)

`$uninstallString = `$null
`$quietUninstallString = `$null

foreach (`$regPath in `$registryPaths) {
    try {
        `$uninstallKeys = Get-ItemProperty `$regPath -ErrorAction SilentlyContinue | Where-Object {
            `$_.DisplayName -like '*$DisplayName*' -or
            `$_.DisplayName -like '*$firstToken*' -or
            `$_.PSChildName -like '*$($PackageId.ToLower())*' -or
            `$_.PSChildName -like '*$PackageId*'
        }

        if (`$uninstallKeys) {
            foreach (`$key in `$uninstallKeys) {
                if (`$key.DisplayName -like '*$firstToken*' -or `$key.DisplayName -like '*$DisplayName*') {
                    `$uninstallString = `$key.UninstallString
                    `$quietUninstallString = `$key.QuietUninstallString
                    Write-Host "Found uninstall string: `$uninstallString"
                    break
                }
            }
            if (`$uninstallString) { break }
        }
    }
    catch {
        Write-Host "Error checking registry path `$regPath : `$_"
    }
}

if (-not `$uninstallString) {
    Write-Host "Uninstall string not found in registry for `$packageId"
    Stop-Transcript
    exit 1
}

`$uninstallCmd = if (`$quietUninstallString) { `$quietUninstallString } else { `$uninstallString }

if (`$uninstallCmd -notmatch '/S' -and `$uninstallCmd -match '\.exe') {
    `$uninstallCmd = `$uninstallCmd -replace '"([^"]+\.exe)"', '"`$1" /S'
    Write-Host 'Added /S flag for silent uninstall'
}

Write-Host "Executing uninstall command: `$uninstallCmd"

try {
    `$process = Start-Process -FilePath 'cmd.exe' -ArgumentList "/c `$uninstallCmd" -Wait -PassThru -NoNewWindow

    if (`$process.ExitCode -eq 0) {
        Write-Host "Package `$packageId uninstalled successfully"
        Stop-Transcript
        exit 0
    }

    Write-Host "Uninstall returned exit code: `$(`$process.ExitCode)"
    Stop-Transcript
    exit `$process.ExitCode
}
catch {
    Write-Host "Error during uninstall: `$_"
    Stop-Transcript
    exit 1
}
"@
}

function Get-WingetterIntunePowerShellCommand {
    param(
        [Parameter(Mandatory = $true)]
        [string]$ScriptFileName
    )

    return "%windir%\sysnative\windowspowershell\v1.0\powershell.exe -WindowStyle Hidden -ExecutionPolicy Bypass -File $ScriptFileName"
}

Export-ModuleMember -Function @(
    'New-WingetterInstallScript'
    'New-WingetterDetectionScript'
    'New-WingetterUninstallScript'
    'Get-WingetterIntunePowerShellCommand'
    'Get-WingetterRegistryVersion'
)
